services:
  - type: web
    name: todo-denojs
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /
    autoDeploy: true 